/// Flutter icons EvergloIcon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EvergloIcon
///      fonts:
///       - asset: fonts/EvergloIcon.ttf
///
///
///
library;
import 'package:flutter/widgets.dart';

class EvergloIcon {
  EvergloIcon._();

  static const _kFontFam = 'EvergloIcon';
  static const String? _kFontPkg = null;

  static const IconData greenhouse =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water_ph =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water_tank =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData air_temperatur =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blower =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heater =
      IconData(0xeba9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homesvg =
      IconData(0xebaa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plant =
      IconData(0xebab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plant_fill =
      IconData(0xebac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile =
      IconData(0xebad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pump =
      IconData(0xebae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scan =
      IconData(0xebaf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water =
      IconData(0xebb0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water_electric =
      IconData(0xebb1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water_faucet =
      IconData(0xebb2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water_part =
      IconData(0xebb3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
