name: everglo_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_dynamic_icon: ^2.1.0
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  get: 4.6.6
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png
    - assets/images/bubbleLogo.png
    - assets/images/mail.png
    - assets/images/password.png
    - assets/images/hideEyes.png
